version: '3.8'
services:
  web:
    build: ./docker/web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  backend:
    build: ./docker/backend
    volumes:
      - type: bind
        source: ./source/backend
        target: /home/backend
  frontend:
    build: ./docker/frontend
    ports: # TODO: Nginxでプロキシする
      - 3000:3000
    volumes:
      - type: bind
        source: ./source/frontend
        target: /home/frontend
    command: sh -c "npm install && npm start"
  database:
    build: ./docker/database
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    platform: linux/amd64
volumes:
  db-store:
